# Generated by Django 4.2.10 on 2026-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('experience_level', models.CharField(choices=[('Entry Level', 'Entry Level (0-2 years)'), ('Mid Level', 'Mid Level (3-5 years)'), ('Senior Level', 'Senior Level (5+ years)')], default='Entry Level', max_length=50)),
                ('location', models.CharField(default='Remote / Hybrid', max_length=100)),
                ('salary', models.CharField(default='$80,000 - $110,000 / year', max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Remote', 'Remote')], default='Full-Time', max_length=50)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_url', models.URLField(default='https://example.com/careers')),
                ('is_sample_data', models.BooleanField(default=True, help_text='Designates realistic sample benchmark job data')),
                ('preferred_skills', models.ManyToManyField(blank=True, related_name='preferred_in_jobs', to='skills.skill')),
                ('required_skills', models.ManyToManyField(related_name='required_in_jobs', to='skills.skill')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
