# Generated by Django 4.2.10 on 2026-08-31 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=100)),
                ('hours_per_day', models.IntegerField(default=2)),
                ('days_per_week', models.IntegerField(default=5)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('phase_name', models.CharField(default='Month 1: Fundamentals', max_length=100)),
                ('priority', models.CharField(choices=[('High Priority', 'High Priority'), ('Medium Priority', 'Medium Priority'), ('Low Priority', 'Low Priority')], default='High Priority', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('estimated_hours', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap.roadmap')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
