# Generated by Django 4.2.10 on 2026-08-31 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, help_text='e.g. Master of Computer Applications (MCA)', max_length=100)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('experience_level', models.CharField(choices=[('Entry Level', 'Entry Level (0-2 years)'), ('Mid Level', 'Mid Level (3-5 years)'), ('Senior Level', 'Senior Level (5+ years)')], default='Entry Level', max_length=50)),
                ('current_role', models.CharField(blank=True, default='Student / Job Seeker', max_length=100)),
                ('target_role', models.CharField(choices=[('Python Developer', 'Python Developer'), ('Django Developer', 'Django Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Backend Developer', 'Backend Developer'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('AI Engineer', 'AI Engineer'), ('Software Developer', 'Software Developer')], default='Python Developer', max_length=100)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('career_goal', models.TextField(blank=True, default='Looking to build a successful career in software development and AI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
