# Generated by Django 4.2.10 on 2026-08-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='expected_salary',
            field=models.CharField(blank=True, help_text='e.g. $80,000 / yr or ₹10 LPA', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='key_skills',
            field=models.CharField(blank=True, help_text='e.g. Python, Django, REST API, React, SQL', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notice_period',
            field=models.CharField(choices=[('Immediate', 'Immediate / Serving Notice'), ('15 Days', '15 Days'), ('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], default='Immediate', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_work_mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site'), ('Flexible', 'Flexible')], default='Remote', max_length=50),
        ),
    ]
