# Generated by Django 4.2.10 on 2026-08-31 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Programming Language', 'Programming Language'), ('Web Framework', 'Web Framework'), ('Database', 'Database'), ('Data Science & AI', 'Data Science & AI'), ('Cloud & DevOps', 'Cloud & DevOps'), ('Tools & Version Control', 'Tools & Version Control'), ('Soft Skills', 'Soft Skills')], default='Programming Language', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_extracted', models.BooleanField(default=True, help_text='Extracted automatically from resume')),
                ('is_target', models.BooleanField(default=False, help_text='Target skill to learn for career goal')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_associations', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill', 'is_target')},
            },
        ),
    ]
